language: php

php:
  - 7.4


matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true


install:
  - composer install --dev --no-interaction


script:
  - mkdir -p build/logs
  - composer test
  - mv build/logs/clover.xml ./coverage.xml


after_success:
  - bash <(curl -s https://codecov.io/bash)
